// Generated by Wrangler on Wed Oct 09 2024 17:23:16 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	TWITCH_CLIENT_ID: string;
	TWITCH_CLIENT_SECRET: string;
	TWITCH_APP_ACCESS_TOKEN: string;
	INDEXER_QUEUE: Queue;
	VECTORIZE: VectorizeIndex;
	AI: Ai;
}
